---
- hosts: tachikoma
  become: yes
  roles:
    - role: caddy-ansible
      caddy_setcap: yes
      caddy_pgp_verify_signatures: yes
      # tls needs to be re-enabled once DNS has been updated
      caddy_config: |
        http://queeriouslabs.com http://35.212.195.155 {
          root /var/www/queeriouslabs.com/deployed
          tls off

          proxy /webhooks localhost:3000
        }
      