---
- hosts: tachikoma
  become: yes
  tasks:
    - name: Install utilities
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - emacs-nox
          - psmisc
          - nano
          - strace
