---
- hosts: tachikoma
  become: yes
  roles:
    - role: caddy-ansible
      caddy_setcap: yes
      caddy_pgp_verify_signatures: yes
      # tls needs to be re-enabled once DNS has been updated
      caddy_config: |
        queeriouslabs.com {
          root /var/www/queeriouslabs.com/deployed
          tls sysadmins@queeriouslabs.com

          proxy /webhooks localhost:3000
          proxy /wiki localhost:3010
        }

        http://35.212.195.155,
        queeriouslabs.net,
        www.queeriouslabs.net,
        queeriouslabs.org,
        www.queeriouslabs.org,
        www.queeriouslabs.com {
          redir https://queeriouslabs.com{uri}
        }


      