---
  # Setup the static website
- hosts: tachikoma
  become: yes
  become_user: www-data
  tasks:
    - name: Create working directory
      become_user: root
      file:
        path: /opt/webhooks
        owner: www-data
        group: www-data
        state: directory
    - name: Install git
      become_user: root
      apt:
        name: git
        state: present
    - name: Clone site repo
      git:
        repo: 'https://github.com/queeriouslabs/webhooks'
        dest: /opt/webhooks
    - name: Template webhook secrets
      template:
        src: webhooks/secrets.json.j2
        dest: /opt/webhooks/secrets.json
    - name: Remove yarn apt key
      become_user: root
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: absent
    - name: Remove yarn apt repo
      become_user: root
      apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: absent
        filename: yarn
    - name: Install node
      become_user: root
      apt:
        name: nodejs
        state: present
        update_cache: true
    - name: Install npm
      become_user: root
      apt:
        name: npm
        state: present
        update_cache: true
    # Requires ansible 2.8+ (switch over later)
    #- name: Install node
    #  snap:
    #    name: node
    #    classic: yes
    - name: Remove yarn
      become_user: root
      apt:
        name: yarn
        state: absent
        update_cache: true
    - name: Install
      become_user: root
      shell:
        npm i -g yarn
      args:
        chdir: /opt/webhooks
    - name: Build
      shell:
        yarn install && yarn run build
      args:
        chdir: /opt/webhooks
    - name: Copy systemd unit file
      become_user: root
      copy:
        src: webhooks/webhooks.service
        dest: /etc/systemd/system/webhooks.service
    - name: Start Webhooks
      become_user: root
      systemd:
        name: webhooks
        daemon_reload: yes
        enabled: yes
        state: restarted
